"""migration

Revision ID: 0d655cb15517
Revises: ee361b520dc8
Create Date: 2025-08-21 16:42:59.788823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d655cb15517'
down_revision = 'ee361b520dc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('column_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'project_column', ['column_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('column_id')

    # ### end Alembic commands ###
