"""otmen

Revision ID: 241360e95073
Revises: aead279e13f2
Create Date: 2025-07-03 15:55:54.018152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '241360e95073'
down_revision = 'aead279e13f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('users_role_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('users_role_key'), ['role'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
