"""migration

Revision ID: 5bcb5f686747
Revises: 0d655cb15517
Create Date: 2025-08-28 14:28:11.214870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bcb5f686747'
down_revision = '0d655cb15517'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(), nullable=True))
        batch_op.drop_column('user_status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_status', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('status')

    # ### end Alembic commands ###
