"""migration

Revision ID: 709e09e8f3b9
Revises: f452fcfa30ae
Create Date: 2025-08-29 17:57:22.523033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '709e09e8f3b9'
down_revision = 'f452fcfa30ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('column_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'project_column', ['column_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('column_id')

    # ### end Alembic commands ###
