"""migration

Revision ID: 71050261387c
Revises: b9f15620432f
Create Date: 2025-07-10 16:16:32.279753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71050261387c'
down_revision = 'b9f15620432f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('priority', sa.String(), nullable=True))
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('priority')

    # ### end Alembic commands ###
