"""migration

Revision ID: 88d7d575f077
Revises: edc645c938e6
Create Date: 2025-07-08 15:17:58.925647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88d7d575f077'
down_revision = 'edc645c938e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_column', schema=None) as batch_op:
        batch_op.add_column(sa.Column('column', sa.String(), nullable=False))
        batch_op.drop_column('title')

    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_frozen', sa.Boolean(), nullable=True))
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column('is_frozen')

    with op.batch_alter_table('project_column', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column('column')

    # ### end Alembic commands ###
