"""migration

Revision ID: ee361b520dc8
Revises: e4c0e36e5512
Create Date: 2025-08-21 16:37:13.404195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee361b520dc8'
down_revision = 'e4c0e36e5512'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_column_many')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_column_many',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('column_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['column_id'], ['project_column.id'], name=op.f('project_column_many_column_id_fkey')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('project_column_many_project_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('project_column_many_pkey'))
    )
    # ### end Alembic commands ###
