"""migration

Revision ID: f452fcfa30ae
Revises: 65c0128e6023
Create Date: 2025-08-29 17:54:06.275004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f452fcfa30ae'
down_revision = '65c0128e6023'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('column_id', sa.String(), nullable=True))
        batch_op.drop_constraint(batch_op.f('todos_project_id_fkey'), type_='foreignkey')
        batch_op.drop_column('project_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('todos_project_id_fkey'), 'projects', ['project_id'], ['id'])
        batch_op.drop_column('column_id')

    # ### end Alembic commands ###
