"""migration

Revision ID: ffb97bfe8eaf
Revises: 82d975ef0de4
Create Date: 2025-06-28 18:26:13.115980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffb97bfe8eaf'
down_revision = '82d975ef0de4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team_lead_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['team_lead_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('team_lead_id')

    # ### end Alembic commands ###
